language: swift
osx_image: xcode9.1
cache: bundler

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
    - env
    - locale
    - brew update
    - brew upgrade carthage || true
    - carthage version
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Check if the library described by the podspec can be built
    - carthage bootstrap

    - echo Build as static library
    - xcodebuild clean build -project WBLanguage.xcodeproj -scheme 'WBLanguage iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c

    - echo Build as dynamic framework
    - xcodebuild clean build -project WBLanguage.xcodeproj -scheme 'WBLanguage iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c

    - echo Build the Demo apps
    - xcodebuild clean build -project WBLanguage.xcodeproj -scheme 'WBLanguage' -configuration Debug -destination 'name=iPhone 7' | xcpretty -c

after_success:
    - bash <(curl -s https://codecov.io/bash)
